services:
  - type: web
    name: excel-to-asc-converter
    env: python
    plan: free
    region: oregon
    buildCommand: |
      python --version
      pip install --upgrade pip setuptools wheel
      pip install --only-binary=all --no-compile -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --max-requests 50 --preload app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_ENV
        value: production
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: SETUPTOOLS_USE_DISTUTILS
        value: stdlib
    healthCheckPath: / 